### ISSUE TITLE
Login on multiple Dates 

### ISSUE THREAD

**Issue by dsyrucek** [academic-moodle-cooperation/moodle-mod_organizer#101]

**Comment by stdoma** [comment]
Hi!
Our teachers ask if it is possible for students to register for several dates at the same time.
I'm assuming that's not possible as the activity can be rated.

Is it conceivable that past timeslots delete themselves?
This would automatically activate students who already had an timeslot.
This could be implemented in connection with the status of non-rating.
The management of organizers for office hours would be greatly simplified.

**Comment by bluetom** [comment]
With the current organizer versions 4.2 and 3.11.7 the multibooking feature has been introduced: Students can now have multiple bookings at the same time.
We will consider to implement an option to delete past timeslots automatically for the complete new organizer which is due to be published by the end of the year 2023.
