### ISSUE TITLE
Organizer v4.1.3 version not working

### ISSUE THREAD

**Issue by JL-MM** [academic-moodle-cooperation/moodle-mod_organizer#135]
Hello,
We tried installing the newest version of mod_organizer but it shows an error message when you try to look at the timeslots (picture bellow). 
![Screenshot - 2024-04-22T130346 310](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/assets/108659217/84354ec0-f58e-4520-8976-591b4dfa5efc)
The same error is displayed if you create new activity and on old Organaiser activitites. Our Moodle version is 4.1.10.

**Comment by bluetom** [comment]
Hi,
I would need more information:
Please reproduce the bug with debug mode "PHP Developer" on and/or have a look in the php logs and send me the tracking informations so that I can locate the error.
Very strange that a version, which is working for so many sites, causes such fundamental problems at your site.
Where did you download the new organizer version - moodle.org, github?
Please ensure that you are not running a mixed version by purging all caches.
And if nothing works you could try to install organizer version 4.2 by hacking the "required" Moodle version in the version.php of the plugin to match your Moodle installation. It should run with Moodle 4.1 without problems...

**Comment by JL-MM** [comment]
Thank you for your quick reply, here's some more information. Screenshot with the debug mode on:
![Screenshot - 2024-04-22T142644 896](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/assets/108659217/4b8212d5-10d8-4587-ac9f-6bead38159e9)
The version was downloaded from moodle.org and I tried purging all caches without any change. I also found a discussion that indicates someone else having similar issue: https://moodle.org/mod/forum/discuss.php?d=456243

**Comment by bluetom** [comment]
Do you run a php-Version prior to 8.0...?

**Comment by JL-MM** [comment]
Yes, we are still running version 7.4

**Comment by haiksu** [comment]
Moodle 4.1 is supposed to officially support PHP 7.4 (as shown here https://moodledev.io/general/releases/4.1).

**Comment by bluetom** [comment]
We published a hotfix version 4.1.4 for php 7.4-compatibility a few minutes ago: https://moodle.org/plugins/mod_organizer/v4.1.4/31830
