### ISSUE TITLE
Database column notified

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_organizer#18]
Hi there,

this is related to the fixed issue #15 .
We applied your patch that fixed the bug. Thanks for this!

Nevertheless, I've got some database questions concerning the appointment reminder messaging.

Old appointments don't send out messages anymore but the value in mdl_organizer_slot_appointments does not change (0). This is a bit confusing for me.

Furthermore, in mdl_organizer_slots there's also a column 'notified'. However the values there always stay 0 and it seems that they are not used anywhere. If this column is not used, it would be consistent to delete this column from the database table.

Cheers,
Kathrin

**Comment by mkemmerling** [comment]
Well, these are plugin internals and as long as the functionality is not affected we won't update the current release. The currently unused column 'notified' might go away or not in some future version.

**Comment by abias** [comment]
Hi Markus,

thanks for your feedback. I dare to contradict you, but I think your strategy to deal with Kathrin's report is wrong.

You're right, the functionality is ok after #15 has been fixed. But there is still wrong / misleading / obsolete data in the database about the status of the user notifications and you are only relying on the fact that the current code knows how to interpret this data in the right way.

In my opinion, you should 
a) set notified in mdl_organizer_slot_appointments to 1 for all appointments which have been in the past by an upgrade script in your next minor release.
b) drop the notified column from mdl_organizer_slots in your next major release at the latest.

Just my two cents.

Thanks,
Alex

**Comment by bluetom** [comment]
Hi Alexander,

I'm the present programmer in charge of the organizer and I'm currently working hard on a long list of new features and changes to improve the organizer for the forthcoming new major release.
Of course, we will fix this in the future, but the issue will not be prioritized highly at the moment since the functionality is ok and the bug has been fixed.
Thank you and Kathrin for informing us of this issue, but please be patient...

Cheers,
Thomas

**Comment by abias** [comment]
Hi Thomas,

thanks for your feedback. I fully appreciate your work on this plugin and I agree that our report does not have highest priority.

Your statement that the problem will be fixed is different from Markus' statement that the problem may be fixed or not and that's what I was complaining about.

Thanks,
Alex

**Comment by mkemmerling** [comment]
Alex, let me be clear: We provide AMC plugins as a free service to the community. We appreciate bug reports and try to fix them. We also consider implementing feature requests coming from the community if they can be implemented with reasonable effort. You know all that. But there is no guarantee for one or the other. That's all what I said (beside the fact that we do not consider a currently unused database field important enough to provide a hot fix).

What I for my part do not appreciate is other people telling us how to do our work (do this in the next minor relate, do that in the next major release). You are always free to implement the fixes in your local plugin installation yourself.

**Comment by abias** [comment]
Hi Markus,

> We provide AMC plugins as a free service to the community. We appreciate bug reports and try to fix them. We also consider implementing feature requests coming from the community if they can be implemented with reasonable effort. You know all that. 

Yes, I know all that. We are working exactly in the same way for our own plugins.

> But there is no guarantee for one or the other. That's all what I said (beside the fact that we do not consider a currently unused database field important enough to provide a hot fix).

On the technical level, I agree with you. There's no need to provide a hot fix just to get rid of a database column (referring to Kathrin's second question). But I hope you also agree with me that mistakable data in the database should be fixed sometime soon to prevent problems in the future (referring to Kathrin's first question).

I think the only disagreement we are facing here is on the communication level:
You answered that the problem may be fixed or not and closed the ticket here in Github. Getting such an answer is rather disappointing because we don't know if the problem will be fixed by you (and when) or if we have to hack our local installation instead.

> What I for my part do not appreciate is other people telling us how to do our work (do this in the next minor relate, do that in the next major release). 

Well, I apologize if my demand for getting something like a schedule was too rude for you.

> You are always free to implement the fixes in your local plugin installation yourself.

Sure, we can fix problems and add features in our own installation. But in my humble opinion, this is not how open source community projects like Moodle should work. We do our best to give all bugfixes, feature requests and patches back to the core developers, plugin maintainers and upstream managers - to our own benefit (because we don't have to maintain plugin forks and core hacks), to your benefit (because you get feedback about your product which may improve its quality) and to all user's benefit who are also using your plugin.

In the end, I don't want to argue with you at all. Therefore, let's leave it at that.

Thanks,
Alex
