### ISSUE TITLE
Trainer is able to assign more than one slot to specific student

### ISSUE THREAD

**Issue by mariofroeschl** [academic-moodle-cooperation/moodle-mod_organizer#54]
This issue was fixed in Organizer v3.5.5 (according to changelog: #6066), but occurs again in v3.5.6.
Although this seems to be a feature delivered with the next major release, it should be possible to turn it off in the Settings.
(Tested on Moodle v3.5.5)

**Comment by goggo24** [comment]
Thanks for reporting. You are right, it should be fixed with v3.5.5+. the way, that it is possible to assign another slot (click button) but only the first assigned slot will be displayed. On the second assignment, no registration is carried out. It loosk like we lost the fix with v.3.5.6. again. We will have a look!

**Comment by goggo24** [comment]
Fix is included in 3.5.7+ and v.3.7.0.  - coming soon!
