### ISSUE TITLE
Students can see identity fields of other students

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-mod_organizer#67]
Set "Visibility of members - presetting" to either

- Visible or
- Only visible to slot members

and set "Max. participants" to something > 1 when creating new slots. Then have two students register for the same slot. The students can see each other's idnumber under "My slot". This information isn't visible under "Slot overview".

This can be prevented by removing "idnumber" from $CFG->showuseridentity. But we need it there for various other reasons, e.g. so that the idnumber is included in grade exports.

It would be nice if the displaying of this information was linked to a capability, so we could take that capability away from out students without changing the behavior for other Moodle instances.

**Comment by goggo24** [comment]
Thanks for reporting. Normally students should never see the idnumbers of other students due to the protection of personal data. In the "slot overview" it's correct and it looks like that only "my slot" isn't displayed correct - that wasn't our intension. The idnumber should only be visible for teachers. 
If we correct the view under "my slot" - it should be fine for you too or?

**Comment by t-schroeder** [comment]
Sure. I just mentioned capabilities as an example. If you can fix it without adding any new capabilities - even better.

**Comment by goggo24** [comment]
fix included in v.3.11.2 - thanks for reporting.
