### ISSUE TITLE
Remove user from Appointment

### ISSUE THREAD

**Issue by SebastianZiegler** [academic-moodle-cooperation/moodle-mod_organizer#80]
Is there a way for an trainer to remove an user from an appointment, didn't find anything.

**Comment by kmelbinger** [comment]
Hello, we are also very interested in this feature, are there any news on this?

**Comment by alina-kiz** [comment]
Hi, we are also interested in the ability  for an trainer to remove a user from an appointment.

**Comment by bluetom** [comment]
This feature is implemented in the current versions 3.11.7 and 4.2.

**Comment by daniil-berg** [comment]
@bluetom This is great. It would be nice, if you could point to the documentation showing _how_ you can remove a user from an appointment. I could not find it there.
Also, am I correct to assume from your last comment that `MOODLE_311_STABLE` and `MOODLE_402_STABLE` are the only branches with this feature? Is there a reason why this is not present in e.g. the other Moodle 4 branches? Could this be merged there too.
By the way, if you link the specific commit or PR introducing a feature in such a comment, rather than simply closing the issue, it becomes much easier for others to follow the development.
